### ISSUE TITLE
Ability to set build dir to module name, not release name

### ISSUE THREAD

**Issue by ekohl** [puppetlabs/puppet-modulebuilder#28]
## Use Case

I would like to be able to build to `target/modules/apache` instead of `target/modules/puppetlabs-apache-1.2.3`. I can achieve `target/modules` instead of `./pkg` via the destination constructor argument, but the release name is not configurable. It can only be set via an instance variable.

## Describe the Solution You Would Like

There should be a way to achieve this without touching private instance variables.

## Describe Alternatives You've Considered

* Constructor parameter
* Subclass
* Method to set build behavior
* Attribute setter

I'm not sure which one of these is the cleanest implementation from an API perspective. I can write a patch for each version, but want to get input on the cleanest way.

## Additional context

I wrote [a script](https://gist.github.com/ekohl/6d22cd2abc30dbf743071ebdcde04b0f) to deploy my Puppet environment to production. I still haven't migrated to r10k and still use git submodules. This makes it easy to work with development versions of the Puppet modules I work on.

It essentially builds a staging directory to deploy to. I use puppet-modulebuilder to create a production-like build (exclude specs, dev files) and then rsync over the staging directory (https://github.com/puppetlabs/puppet-modulebuilder/pull/27 already improves this by maintaining mtimes on directories, creating a smaller rsync).

There is one ugly hack in my script:

```ruby
builder.instance_variable_set(:@release_name, File.basename(t.name))
```

**Comment by DavidS** [comment]
Since this seems like a generally optional configuration item, I'd suggest adding a setter to https://github.com/puppetlabs/puppet-modulebuilder/blob/1d47cce6a02b891f109261ec467784b3ba7f1360/lib/puppet/modulebuilder/builder.rb#L328-L333

That way your script can avoid the nasty `instance_variable_set`, and it has little to no effect on everyone else.

**Comment by ekohl** [comment]
Thanks! #31 should do that.
