### ISSUE TITLE
Reconsider Gem namespace

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/puppet-modulebuilder#3]
Currently the Gem lives in the `Puppet` namespace which may have unintended consequences:

e.g.
* module name conflicts with the real puppet gem
* Difficulty in debugging because the name implies it's in the `puppet` gem

Usual convention is start with the Gem name so `puppet-modulebuilder/...` and `PuppetModulebuilder::` would be preferred

**Comment by DavidS** [comment]
This would require renaming everything from `puppet-modulebuilder` to `puppet_modulebuilder` to match with ruby naming conventions.

* if we can't coordinate namespace within the org, we're doomed in deeper ways.
* plugins/components inside a common namespace is well-established ruby pattern (see all the beaker-* gems; rspec-*)

**Comment by glennsarti** [comment]
Fair enough.
